# name: Github Workflow
# on: workflow_dispatch
# jobs:
#   first-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Greeting Message
#         run: echo "Welcome to github"
#       - name: Seeof Message
#         run: echo "Bye from github"
        
name: Github Workflow Demo
on: push
jobs:
  Checkout_Code_and_Install_Dependencies :
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code from Github Repo
        uses: actions/checkout@v4
      - name: Install Node JS Version
        uses : actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Run Test Cases
        run: npm test
  Deploy:
    needs: Checkout_Code_and_Install_Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code from Github Repo
        uses: actions/checkout@v4
      - name: Install Node JS Version
        uses : actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Code
        run: npm run build
    


      
      
  
