# name: Github Workflow
# on: workflow_dispatch
# jobs:
#   first-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Greeting Message
#         run: echo "Welcome to github"
#       - name: Seeof Message
#         run: echo "Bye from github"
        
name: Github Workflow Demo
on: [push, workflow_dispatch]
jobs:
  Lint :
    runs-on: ubuntu-latest
    steps:
      - name: Run Linting
        uses: actions/checkout@v4
      - name: Install Node JS Version
        uses : actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  Test :
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Run Linting
        uses: actions/checkout@v4
      - name: Install Node JS Version
        uses : actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  Deploy:
    needs: [Test, Lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Get the Code from Github Repo
        uses: actions/checkout@v4
      - name: Install Node JS Version
        uses : actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Build Code
        run: npm run build
      # - name: Github Context Data  
      #   run: echo "${{ toJSON(github) }}"
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: output-build
          path: |
                output-build-files
                package.json
                readme.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: binary-${{ matrix.os }}-${{ matrix.version }}
          path: my-binary

    


      
      
  
